apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gpmd-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
   - http:
      paths: 
      - path: /formui/?(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-formbuilderui-service
          servicePort: {{ .Values.formbuilderui.service.port }}
      - path: /formapi/?(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-formbuilderapi-service
          servicePort: {{ .Values.formbuilderapi.service.port }}
      - path: /dashboardui/?(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-dashboardbuilderui-service
          servicePort: {{ .Values.dashboardbuilderui.service.port }}
      - path: /dashboardapi/?(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-dashboardapi-service
          servicePort: {{ .Values.dashboardapi.service.port }}    